name: Compiler sandbox

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.3
    - uses: VirtusLab/scala-cli-setup@v1

    - name: Compile stable
      run: scala-cli compile .
      
    - name: Compile nightly
      run: scala-cli -S 3.nightly compile .