name: Compiler sandbox

on:
  push:

jobs:
  test_release:
    runs-on: ubuntu-latest
    container:
      image: lampepfl/dotty:2024-10-18
      options: --cpu-shares 4096
      volumes:
        - ${{ github.workspace }}/../../cache/sbt:/root/.sbt
        - ${{ github.workspace }}/../../cache/ivy:/root/.ivy2/cache
        - ${{ github.workspace }}/../../cache/general:/root/.cache
    steps:
      - name: Set JDK 8 as default
        run: echo "/usr/lib/jvm/java-8-openjdk-amd64/bin" >> $GITHUB_PATH

      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Create stubs 
        shell: bash
        run: |
          echo "test-release-asset" > asset.txt
          echo "test-release-asset" > asset2.txt
          echo "RELEASE_TAG=${1.2.3-RC1}" >> $GITHUB_ENV
      
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.2.0
        with:
          gh-cli-version: 2.59.0 
          
      # Create the GitHub release
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        shell: bash
        run: |
          gh release create \
          --draft \
          --title "${{ env.RELEASE_TAG }}" \
          --latest=${{ !contains(env.RELEASE_TAG, '-RC') }} \
          --prerelease=${{ contains(env.RELEASE_TAG, '-RC') }} \
          ${{ env.RELEASE_TAG }} \
          asset*.txt
          
  
  build:
    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        OS: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
    - name: Setup env
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.3
    - uses: VirtusLab/scala-cli-setup@v1

    - name: Compile stable
      run: scala-cli run .

    - name: Compile nightly
      run: scala-cli run -S 3.nightly .

    - name: Compile LTS
      run: scala-cli run -S 3.lts .